### Get all cats
GET http://localhost:8080/api/cats


### Get cat by id
GET http://localhost:8080/api/cats/1


### Create new cat
POST http://localhost:8080/api/cats
Content-Type: application/json

{
  "name": "Hazel",
  "breed_id": 5,
  "owner_id": 8,
  "birth_date": "1999-09-03T22:21:09.264528",
  "images": ["", "", ""],
  "toys": ["", "", ""]
}