cf:
  welcome-message: THIS IS PRODUCTION!!!
  about: this api is just a sample project using spring boot in PRODUCTION


# adding production database and stuff can be here!
spring:

  datasource:
    url: jdbc://postgresql:${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
