spring:
  config:
    import: env.properties
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

# Will execute sql
#  sql:
#    init:
#      mode: always

logging:
  level.org.springframework.jdbc=DEBUG

debug: true