spring:
  config:
    import: env.properties
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}


#  profiles:
#    default: "dev"



# Will execute sql
#  sql:
#    init:
#      mode: always
#  sql:
#    init:
#      schema-locations:
#  sql:
#    init:
#      data-locations:

logging:
  level:
#    root: "warn"
#    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG

debug:
  true

server:
  port=${PORT}:

