spring:
  config:
    import: env.properties
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  profiles:
    active: dev





# Will execute sql
#  sql:
#    init:
#      mode: always
#  sql:
#    init:
#      schema-locations:
#  sql:
#    init:
#      data-locations:

logging:
  level:
#    root: "warn"
#    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG

#debug:
#  true

# will be overridden by
# Run -> Edit Configurations -> Modify Options -> Environment Variables

# Choosing the port
server:
  port=${PORT}

#server:
#  port: 8080


cf:
  welcome-message: Welcome to cat finder
  about: this api is just a sample project using spring boot


# adding dev database and stuff can be here!


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true